site_name: ayon-launcher
repo_url: https://github.com/ynput/ayon-launcher

nav:
  - Home: index.md
  - License: license.md
  - Build Guides:
    - Windows: docs/build_guides/windows.md
    - Linux: build_guides/linux.md
    - Mac OS: build_guides/macos.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  logo: img/ay-symbol-blackw-full.png
  favicon: img/favicon.ico
  features:
    - navigation.sections
    - navigation.path
    - navigation.prune

extra:
  version:
    provider: mike

extra_css: [css/custom.css]

markdown_extensions:
  - mdx_gh_links
  - pymdownx.snippets

plugins:
  - search
  - offline
  - mkdocs-autoapi:
      autoapi_dir: ./
      autoapi_add_nav_entry: Reference
      autoapi_ignore:
        - .*
        - docs/**/*
        - ./**/tests/**/*
        - tools/**/*
        - stubs/**/*        # mocha fix
        - ./**/pythonrc.py  # houdini fix
        - .*/**/*
        - mkdocs_hooks.py
        - vendor/**/*.py
        # - ./*.py
  - mkdocstrings:
      handlers:
        python:
          paths:
            - ./
            - client/*
            - server/*
            - services/*
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
  - mike

hooks:
  - mkdocs_hooks.py
