[tool.poetry]
name = "AYON-shim"
version = "1.0.0"
description = "Open VFX and Animation pipeline with support."
authors = ["Ynput s.r.o. <info@ynput.io>"]
license = "MIT License"
homepage = "https://ynput.io"
documentation = "https://ayon.ynput.io"
repository = "https://github.com/ynput/ayon-launcher"
package-mode = false
packages = [
    {include = "shim_start.py"},
    {include = "setup.py"},
    {include = "pyproject.toml"},
    {include = "poetry.lock"}
]

[tool.poetry.dependencies]
python = ">=3.9.1,<3.10"
platformdirs = "^3.0.0"
semver = "^2.13.0"

[tool.poetry.group.dev.dependencies]
cx_freeze = "6.15.16"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/ynput/ayon-launcher/issues"
"Discussions" = "https://github.com/ynput/ayon-launcher/discussions"
