name: ðŸš€ Release Build

on:
  release:
    types: [published, created]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'The tag name of the release to upload to (e.g. v1.2.3). If not provided, it will try to find a release for the current ref.'
        required: false
        type: string

jobs:
  build:
    name: Build (${{ matrix.variant }}${{ matrix.use-pyside2 && ' - PySide 2' || '' }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - variant: ubuntu
          - variant: debian
          - variant: rocky8
          - variant: rocky8
            use-pyside2: true
          - variant: rocky9

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag_name || github.ref }}
          submodules: recursive

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Run Docker Build
        shell: bash
        run: |
          chmod +x ./tools/make.sh
          ./tools/make.sh docker-build ${{ matrix.variant }} ${{ matrix.use-pyside2 == true && '--use-pyside2' || '' }}

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: build_${{ matrix.variant }}${{ matrix.use-pyside2 && '_pyside2' || '' }}/installer/*
          tag_name: ${{ inputs.tag_name || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
